Mo's branch 2
Codelikeneverbefore1/the-elephants-habit-app pull request #13
Opened 2023-07-21 01:30 UTC by ombymo

Please check! Cannot test update and delete function properly yet, they work and render out though.

2023-08-04 20:17 UTC, rozaromanova requested changes
@ombymo I can't run your code, getting the following error:
```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/roza.romanova/Documents/TechLabs/habapp-backend/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/roza.romanova/Documents/TechLabs/habapp-backend/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```
I couldn't find why the reference is wrong right away, hence suggest you check your code and see why the package.json is either wrongly place, or addressed incorrectly. Both mine and Lasses' branches have it in habapp-backend/, yours is in habapp-backend/models

2023-08-04 22:02 UTC, ombymo commented
Hey, it HAS TO be there (on same level as habapp-backend). I had it in the backend before, according to main, but it wouldn't run then. It's completely functional, all routes tested on postman, all routes secured with tokens as well.

2023-08-04 22:11 UTC, ombymo commented
But CAN you merge? Because this branch was cloned via html, NOT SSH.

2023-08-04 22:13 UTC, ombymo commented
@rozaromanova inside ../models there's only goalModel and userModel.

2023-08-05 11:28 UTC, rozaromanova commented
@Gw3i can you maybe help out here? I can't run Mo's code, but apparently the other way around he can't run it. What's going wrong?

2023-08-05 20:43 UTC, rozaromanova commented
@Codelikeneverbefore1 do you have a chance to run the app? I pushed the changes that I think should fix the problem for me, but it may break things for others...

2023-08-06 10:13 UTC, ombymo commented
@rozaromanova IT IS FUNCTIONAL, ANYONE CAN RUN IT. Do u maybe need help to run it? Have you checked all necessary dependencies and packages are in place? did u start npm/async/etc. before running?

2023-08-06 10:19 UTC, ombymo commented
<img width="668" alt="Bildschirmfoto 2023-08-01 um 14 36 43" src="https://github.com/Codelikeneverbefore1/the-elephants-habit-app/assets/119120235/f49ce147-340f-4b42-a059-307bf01f8031">
<img width="1282" alt="Bildschirmfoto 2023-08-01 um 14 36 54" src="https://github.com/Codelikeneverbefore1/the-elephants-habit-app/assets/119120235/ac04f5e9-de12-4dd4-84f5-9765e6fada5a">
<img width="1223" alt="Bildschirmfoto 2023-08-01 um 14 37 09" src="https://github.com/Codelikeneverbefore1/the-elephants-habit-app/assets/119120235/bb45e08c-5294-46ef-b74b-8a4d23fb941d">
<img width="1236" alt="Bildschirmfoto 2023-08-01 um 14 37 54" src="https://github.com/Codelikeneverbefore1/the-elephants-habit-app/assets/119120235/cd25ab89-0ee5-4836-98c6-acea3474264e">

2023-08-07 23:05 UTC, rozaromanova commented
(tested how the deleting comments and reporting the behavior works, accidentally closed the branch)
comments for the reference:
https://d.pr/i/0D2MuQ
https://d.pr/i/GeRkZa
https://d.pr/i/VKwZ6v
https://d.pr/i/yxVBuH

2023-08-11 06:26 UTC, Gw3i requested changes

2023-08-11 06:26 UTC, Gw3i commented on habapp-backend/controllers/habitController.js
> +    //console.log(habit)
PLease remove

2023-08-11 06:26 UTC, Gw3i commented on habapp-backend/controllers/habitController.js
> +    //await Habit.deleteOne({ id: req.params.id })
PLwase remove

2023-08-11 06:26 UTC, Gw3i commented on habapp-backend/controllers/habitController.js
> +    console.log(habit2)
Please remove

2023-08-11 06:26 UTC, Gw3i commented on habapp-backend/controllers/userController.js
> +    //res.json({message: 'Register User'})
Please remove

2023-08-11 06:26 UTC, Gw3i commented on habapp-backend/controllers/userController.js
> +    //res.json({message: 'User Data'})
Please remove

2023-08-11 06:26 UTC, Gw3i commented on habapp-backend/models/userModel.js
> +        //unique: true
please remove

2023-08-11 13:31 UTC, ombymo commented on habapp-backend/controllers/habitController.js
> +    //console.log(habit)
und res.status(401) soll drin bleiben?

2023-08-11 13:34 UTC, ombymo commented on habapp-backend/controllers/userController.js
> +    //res.json({message: 'Register User'})
soll ich zeile 43 entfernen oder wie meinst du? den throw error teil

2023-08-11 15:51 UTC, Gw3i commented on habapp-backend/controllers/habitController.js
> +    //console.log(habit)
Zeile 82

2023-08-11 15:51 UTC, Gw3i commented on habapp-backend/controllers/habitController.js
> +    //await Habit.deleteOne({ id: req.params.id })
Zeile 84 und 86

2023-08-11 15:51 UTC, Gw3i commented on habapp-backend/controllers/userController.js
> +    //res.json({message: 'Register User'})
Zeile 47

2023-08-11 15:52 UTC, Gw3i commented on habapp-backend/controllers/userController.js
> +    //res.json({message: 'User Data'})
Zeile 79

2023-08-11 15:52 UTC, Gw3i commented on habapp-backend/models/userModel.js
> +        //unique: true
Zeile 11

2023-08-12 18:38 UTC, Gw3i commented on habapp-backend/server/index.js
> +//please leave as it is. it's all tested on postman already. if anything needs to be adapted for frontend let me know.
Das auch weg, bitte

2023-08-13 09:02 UTC, Gw3i approved these changes

2023-08-17 09:34 UTC, rozaromanova approved these changes

2023-08-17 09:34 UTC, merged